server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /goddess-admin
minio:
  endpoint: 'http://127.0.0.1:9000'
  accessKey: 'minio'
  secretKey: 'minio123456'
  bucketPrefix: 'dev'
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization



